---

- name: install git
  become: yes
  yum: name=git

- name: check out pyenv
  git:
    repo: "{{pyenv_repo_url}}"
    dest: "{{pyenv_install_path}}"
    version: "{{pyenv_version}}"

- name: check out plugins
  git:
    repo: "{{item.repo_url}}"
    dest: "{{pyenv_install_path}}/plugins/{{item.name}}"
    version: "{{item.version | default('HEAD')}}"
  with_items: "{{pyenv_plugins}}"

- name: configure PATH
  blockinfile:
    dest: "{{pyenv_profile_path}}"
    marker: "# {mark} ANSIBLE PYENV BLOCK"
    block: |
      if [ -d "{{pyenv_install_path}}" ]; then
        export PYENV_ROOT={{pyenv_install_path}}
        export PATH=$PYENV_ROOT/bin:$PATH
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
      fi
    follow: yes