---

- name: install dependencies
  become: yes
  yum: name={{item}}
  with_items:
    - "{{ python_dependencies }}"
  when: python_versions|length > 0

- name: install pythons
  include: python.yml
  with_items: "{{python_versions}}"
  loop_control:
    loop_var: version

- name: set to global version
  shell: >
    source {{pyenv_profile_path}} &&
    if ! pyenv version | grep -Eq '^{{python_global_version}} '; then
      pyenv global {{python_global_version}} && echo -e \\nchanged
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: "'changed' in result.stdout_lines"
  when: python_global_version is defined
